### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by rad-lanl**
- Updated geotess/src to version 2.7
- Additional exposures in .pxd, GeoTessModel.getPointWeights*
- Updated [libgeotess.cpp](https://github.com/rad-lanl/PyGeoTess/blob/master/geotess/src/libgeotess.cpp)

### CODE REVIEW

**Comment by rad-lanl** [comment]
Not sure why the pull is attempting to remove geotess/src/EathShape.cc? i'd reject that change if possible
Its in my fork? https://github.com/rad-lanl/PyGeoTess/blob/master/geotess/src/EarthShape.cc

**Review by jkmacc-LANL — APPROVED** [review]
Looks good!  Thank you for keeping additions consistent with existing conventions.  Test failures are on my end; I'll fix them in post.

**Comment by jkmacc-LANL** [comment]
We've still got `EarthShape.cc`.  It looks like someone ran a linter on it; there are just a few whitespace changes.

**Comment by jkmacc-LANL** [comment]
@rad-lanl I don't see `GeoTessModel.getPointWeights` in the CPP source code; where did this come from?

**Comment by RichardAlfaro** [comment]
Yes it’s just calling different signatures of GeoTessModel.getWeights, okay with me to wrap it into a generalized getWeights call

On May 31, 2024, at 2:38 PM, jkmacc-LANL ***@***.***> wrote:

﻿

@rad-lanl<https://github.com/rad-lanl> I don't see GeoTessModel.getPointWeights in the CPP source code; where did this come from?

**Comment by jkmacc-LANL** [comment]
I'll leave that for a later PR, so you don't have to change code.  It should be a straightforward change.

**Pull request merged**
